### ISSUE TITLE
Couple more puzzlers

### ISSUE THREAD

**Issue by dkandalov** [angryziber/kotlin-puzzlers#3]
I haven't seen your presentation but thanks a lot for these great puzzlers!
The puzzlers not detected by IDE static analysis are the best :)

In case you're interested, here are some puzzlers I came across:
 - recently posted on Kotlin slack
```kotlin
val whatAmI = {}()
println(whatAmI)
```
 - power throw!
```kotlin
throw throw throw Exception()
return return 123
```
 - https://youtrack.jetbrains.com/issue/KT-11851
```kotlin
val map = mapOf<Any, Any>().withDefault{ "default" }
println(map["1"])
```
 - http://stackoverflow.com/questions/32993586/templates-escaping-in-kotlin-multiline-strings/

**Comment by angryziber** [comment]
Thanks, I will include these!
The non-compiling puzzlers were mostly for beginners. As we see more people familiar with the language, I am going to omit them.

**Comment by dkandalov** [comment]
Btw, do you mind if I use some of your puzzlers in a talk about Kotlin?
(Mentioning the original source of course.)

**Comment by angryziber** [comment]
Yes, no problem. Where will you give a talk?

**Comment by dkandalov** [comment]
Great, thanks! 
ACCU, Devoxx UK, Riga Dev Days.

**Comment by angryziber** [comment]
Btw, do you have any idea why Kotlin compiler allows multiple `throw` and `return`?

**Comment by dkandalov** [comment]
`Nothing` is subtype of all types so it's ok to return or throw it instead of any other type.
Also found this:
```kotlin
fun `return return`() {
    return return
}
```

**Comment by angryziber** [comment]
That's a good one! :-)
