### ISSUE TITLE
Enum puzzler

### ISSUE THREAD

**Issue by a-dminator** [angryziber/kotlin-puzzlers#5]
enum class E { e }

val e = E.e
val a = when (E.e) {
    e -> "1"
}

fun main(args: Array<String>) {
    print(a)
}

// What will it print?
// a) 1
// b) Will not compile
// c) null
// d) NullPointerException

**Comment by angryziber** [comment]
Submitted a compiler bug:
https://youtrack.jetbrains.com/issue/KT-16202
