### ISSUE TITLE
New puzzler

### ISSUE THREAD

**Issue by rpuxa** [angryziber/kotlin-puzzlers#59]
```
    fun Any.toConsole(): Unit = print("$this  ")

    fun main() {
        val list = listOf(1, 2, 3)
        val array = IntArray(1)

        { 42 }.toConsole()
        list.toConsole()
        array.toConsole()
    }
```

1) [I@3f99bd52  [1, 2, 3]  kotlin.Unit
2) 42  java.util.ArrayList@4481f34a  [I@448139f0
3) kotlin.Unit  [1, 2, 3]  [I@448139f0
4) Function0<java.lang.Integer>  java.util.ArrayList@4481f34a  [I@448139f0
5) Function0<java.lang.Integer>  [1, 2, 3]  [I@448139f0

Correct answer: first. Because { 42 } its a second argument of IntArray constructor

**Comment by SerVB** [comment]
Great catch! I love it. Could you also provide Kotlin version?

**Comment by rpuxa** [comment]
> Great catch! I love it. Could you also provide Kotlin version?

What do you mean?

**Comment by SerVB** [comment]
Is this 1.3.40?

**Comment by rpuxa** [comment]
> Is this 1.3.40?

It works at 1.3.40 and 1.3.41 versions. I've tried
