### ISSUE TITLE
NaN puzzler

### ISSUE THREAD

**Issue by rpuxa** [angryziber/kotlin-puzzlers#64]
val number: Number = 0.0 / 0.0
    println(if (number is Double) number == number else "number !is Double")

a) true
b) false
c) number !is Double
d) None of the above

Correct answer: a. Compiler ignores smart cast to Double and compares numbers like Objects, i.e. using equals() method. And equals() method returns true if it compares two NaNs.

**Comment by rpuxa** [comment]
I ran this code in [kotlin playground](https://pl.kotl.in/BB2hD8Sty) and it returned false, but in IntelliJ IDEA it returns true! WTF?

**Comment by TWiStErRob** [comment]
Playground uses 1.3.41 or 1.3.50, what's your project using?
It could also be a NewInference bug?

**Comment by rpuxa** [comment]
I've tried on 1.3.50 and 1.3.60. Both versions print true.

**Comment by TWiStErRob** [comment]
So we need an option "it depends" 😮.

I also get `true` when pasting the two lines into `kotlinc` 1.3.50

**Comment by rpuxa** [comment]
By the way, one of the things I discovered - if you open Tools >> Kotlin >> Show Kotlin bytecode, it shows wrong bytecode. To figure out how code works i had to use external bytecode viewer.

**Comment by rpuxa** [comment]
And if you change platform to JS on playground it becomes to print true (╯°□°)╯︵ ┻━┻

**Comment by TWiStErRob** [comment]
> (╯°□°)╯︵ ┻━┻

I think you just proved that it's a good puzzler!

**Comment by angryziber** [comment]
I put this into a kts file and it returns false, but yes, pasting to kotlinc returns true.
Probably would need to find somebody to explain this @ KotlinConf :-)
